MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]

c_compiler_version:        # [linux]
  - 9                      # [linux]
cxx_compiler_version:      # [linux]
  - 9                      # [linux]
