{% set name = "libv8" %}
{% set version = "8.6.214" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/v8/v8/archive/{{ version }}.tar.gz
    sha256: 404882d3428d72a27cf25060ebfb79091eee1c1a8ba8b53041f7a14edcc35148
    patches:
      - test-no-unitests.patch
  # We use tarballs but don't add sha256s as they are different on every download.
  # Sychronized hashes from https://github.com/Homebrew/homebrew-core/blob/2a8b9b60c832d25c8b2013d641e49a886ccbe0f7/Formula/v8.rb
  # Hashes can also be retrieved from https://github.com/v8/v8/blob/8.6.214/DEPS
  - url: https://chromium.googlesource.com/chromium/src/build.git/+archive/e2b8e15a06b8f8249fc09426225242139dafc994.tar.gz
    folder: build
    patches:
      - build-remove-compiler-warning.patch
      - build_prefix_rpath.patch  # [osx]
  - url: https://chromium.googlesource.com/chromium/src/third_party/jinja2.git/+archive/3f90fa05c85718505e28c9c3426c1ba52843b9b7.tar.gz
    folder: third_party/jinja2
  - url: https://chromium.googlesource.com/chromium/src/third_party/markupsafe.git/+archive/8f45f5cfa0009d2a70589bcda0349b8cb2b72783.tar.gz
    folder: third_party/markupsafe
  - url: https://chromium.googlesource.com/external/github.com/google/googletest.git/+archive/4fe018038f87675c083d0cfb6a6b57c274fb1753.tar.gz
    folder: third_party/googletest/src
  - url: https://chromium.googlesource.com/chromium/src/base/trace_event/common.git/+archive/23ef5333a357fc7314630ef88b44c3a545881dee.tar.gz
    folder: base/trace_event/common
  - url: https://chromium.googlesource.com/chromium/src/third_party/zlib.git/+archive/89bddfee9cf8fde3ab1212ed63bf03d76baf8914.tar.gz
    folder: third_party/zlib
  - url: https://chromium.googlesource.com/chromium/deps/icu.git/+archive/79326efe26e5440f530963704c3c0ff965b3a4ac.tar.gz
    folder: third_party/icu
    patches:
      - icu-build.patch
      - icu-config.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libv8', max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gn 0.0.20200720112859
    - python <3
    - setuptools
    - ninja
  host:
    - glib
    - icu

test:
  commands:
    - test -f $PREFIX/lib/libv8${SHLIB_EXT}

about:
  home: https://v8.dev/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: V8 is Google’s open source high-performance JavaScript and WebAssembly engine, written in C++.
  dev_url: https://chromium.googlesource.com/v8/v8.git

extra:
  recipe-maintainers:
    - xhochy
