{% set name = "libv8" %}
{% set version = "8.9.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/v8/v8/archive/{{ version }}.tar.gz
    sha256: b82eb16308acafc384f84e3b7d0677015fbdd0c6339204732377a7e5da07904b
    patches:
      - test-no-unitests.patch
  # We tarballs but don't add sha256s as they are different on every download.
  # Sychronized hashes from https://github.com/v8/v8/blob/{{ version }}/DEPS
  - url: https://chromium.googlesource.com/chromium/src/build.git/+archive/49ce9a35fc22efe144eb5bdad9233578eb69e003.tar.gz
    folder: build
    patches:
      - build_prefix_rpath.patch  # [osx]
  - url: https://chromium.googlesource.com/chromium/src/third_party/jinja2.git/+archive/a82a4944a7f2496639f34a89c9923be5908b80aa.tar.gz
    folder: third_party/jinja2
  - url: https://chromium.googlesource.com/chromium/src/third_party/markupsafe.git/+archive/0944e71f4b2cb9a871bcbe353f95e889b64a611a.tar.gz
    folder: third_party/markupsafe
  - url: https://chromium.googlesource.com/external/github.com/google/googletest.git/+archive/4fe018038f87675c083d0cfb6a6b57c274fb1753.tar.gz
    folder: third_party/googletest/src
  - url: https://chromium.googlesource.com/chromium/src/base/trace_event/common.git/+archive/eb94f1c7aa96207f469008f29989a43feb2718f8.tar.gz
    folder: base/trace_event/common
  - url: https://chromium.googlesource.com/chromium/src/third_party/zlib.git/+archive/9893e506b3a7ea4ec68e1fcd9a374e849945f405.tar.gz
    folder: third_party/zlib
  - url: https://chromium.googlesource.com/chromium/deps/icu.git/+archive/7db579a73addda0edb2bb83465ae51bcdc601af7.tar.gz
    folder: third_party/icu
    patches:
      - icu-build.patch
      - icu-config.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libv8', max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gn 0.0.20200909083119
    - python <3
    - setuptools
    - ninja
    - pkg-config
  host:
    - glib
    - icu

test:
  commands:
    - test -f $PREFIX/lib/libv8${SHLIB_EXT}

about:
  home: https://v8.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: V8 is Google’s open source high-performance JavaScript and WebAssembly engine, written in C++.
  dev_url: https://chromium.googlesource.com/v8/v8.git

extra:
  recipe-maintainers:
    - xhochy
