{% set name = "libv8" %}
{% set version = "7.8.87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: "https://github.com/v8/v8/archive/{{ version }}.tar.gz"
    sha256: 67d9b135942f6919eb0f584c5c92d9a71ca8654d36a2b54456616a20e23984ec
  # We tarballs but don't add sha256s as they are different on every download.
  # Hashes from https://github.com/v8/v8/blob/7.8.87/DEPS
  - url: "https://chromium.googlesource.com/chromium/src/build.git/+archive/f3d0ca5f46b7b190dbbdc6be508ca11dd5c54302.tar.gz"
    folder: build
  - url: "https://chromium.googlesource.com/chromium/src/third_party/jinja2.git/+archive/b41863e42637544c2941b574c7877d3e1f663e25.tar.gz"
    folder: third_party/jinja2
  - url: "https://chromium.googlesource.com/chromium/src/third_party/markupsafe.git/+archive/8f45f5cfa0009d2a70589bcda0349b8cb2b72783.tar.gz"
    folder: third_party/markupsafe
  - url: "https://chromium.googlesource.com/external/github.com/google/googletest.git/+archive/90a443f9c2437ca8a682a1ac625eba64e1d74a8a.tar.gz"
    folder: third_party/googletest/src
  - url: "https://chromium.googlesource.com/chromium/src/base/trace_event/common.git/+archive/5e4fce17a9d2439c44a7b57ceecef6df9287ec2f.tar.gz"
    folder: base/trace_event/common
  - url: "https://chromium.googlesource.com/chromium/deps/icu.git/+archive/682a230923933a7157a41b88c7804b6b7d2abdfa.tar.gz"
    folder: third_party/icu
    patches:
      - third_party-icu-use-system-icu.diff

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libv8', max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}  # [not osx]
    - {{ compiler('cxx') }}  # [not osx]
    - clangdev  # [osx]
    - gn
    - python <3
    - setuptools
    - ninja
  host:
    - glib
    - icu =64.2
  run:
    - icu =64.2

test:
  commands:
    - test -f $PREFIX/lib/libv8${SHLIB_EXT}

about:
  home: https://v8.dev/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'V8 is Google’s open source high-performance JavaScript and WebAssembly engine, written in C++.'
  dev_url: https://chromium.googlesource.com/v8/v8.git

extra:
  recipe-maintainers:
    - xhochy
